# name: Terraform Deployment

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   terraform:
#     name: Terraform Deploy
#     runs-on: ubuntu-latest

#     permissions:
#       id-token: write
#       contents: read

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: arn:aws:iam::536697233234:role/Github-OIDC-role
#           role-session-name: GitHubActionsSession
#           aws-region: us-east-1

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.10.0

#       - name: Terraform Init
#         run: terraform init
#         working-directory: infrastructure

#       - name: Terraform Validate
#         run: terraform validate
#         working-directory: infrastructure

#       - name: Terraform Apply
#         run: terraform apply -auto-approve -var-file="terraform.tfvars"
#         working-directory: infrastructure
