name: Terraform Import Existing Resources

on:
  workflow_dispatch:  # manually triggered from GitHub UI

jobs:
  terraform-import:
    name: Terraform Import
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::536697233234:role/Github-OIDC-role
          role-session-name: GitHubActionsImportSession
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure

      - name: Terraform Import Existing Resources
        working-directory: infrastructure
        run: |
          echo "🔄 Importing IAM Role..."
          terraform import aws_iam_role.ecs_task_execution_role ror-app-task-executions-role || echo "⚠️ Already imported or missing"

          echo "🔄 Importing IAM Policies..."
          terraform import aws_iam_policy.s3_access_policy arn:aws:iam::536697233234:policy/ror-app-s3-access || echo "⚠️ Already imported or missing"

          echo "🔄 Importing IAM Role Policy Attachments..."
          terraform import aws_iam_role_policy_attachment.ecs_execution_policy ror-app-task-executions-role/arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy || echo "⚠️ Already imported or missing"
          terraform import aws_iam_role_policy_attachment.s3_access_attach ror-app-task-executions-role/arn:aws:iam::536697233234:policy/ror-app-s3-access || echo "⚠️ Already imported or missing"

          echo "🔄 Importing RDS DB Instance..."
          terraform import aws_db_instance.this db-6OXZRBMLONRVYWHR2HPZF3TIVA || echo "⚠️ Already imported or missing"

          echo "🔄 Importing ALB..."
          terraform import aws_lb.this arn:aws:elasticloadbalancing:us-east-1:536697233234:loadbalancer/app/ror-app-alb/2a3f6dfa6b717a3b || echo "⚠️ Already imported or missing"

          echo "🔄 Importing ALB Listener..."
          terraform import aws_lb_listener.this arn:aws:elasticloadbalancing:us-east-1:536697233234:listener/app/ror-app-alb/2a3f6dfa6b717a3b/36b0e38b8e229f12 || echo "⚠️ Already imported or missing"
